before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq doxygen graphviz
 - sudo sed -i 's/precise/trusty/g' /etc/apt/sources.list
 - gpg --keyserver keyserver.ubuntu.com --recv-keys 3B4FE6ACC0B21F32
 - gpg --export 3B4FE6ACC0B21F32 | sudo apt-key add -
 - sudo apt-get update -qq
 - sudo apt-get install -qq gcc-mingw-w64-i686 g++-mingw-w64-i686 binutils-mingw-w64-i686 g++-4.8
 - sudo ln -sf /usr/bin/gcc-4.8 /usr/bin/gcc;
 - sudo ln -sf /usr/bin/g++-4.8 /usr/bin/g++;

script:
 - make travis-ci-windows
 - make build-only-windows
 - make zip-only-windows
 - make doc
